select * FROM customer_shopping_data;
---Q1. WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE CUSTOMERS?
select gender, SUM(purchase_amount)as revenue
from  customer_shopping_data
group by gender

---Q2. WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT
SELECT
    customer_id,
    purchase_amount
FROM
    customer_shopping_data
WHERE
    discount_applied = 'Yes'
    AND purchase_amount >= (
        -- Subquery: Calculates the average purchase amount from the whole table
        SELECT AVG(purchase_amount)
        FROM customer_shopping_data
)
-- Q3. WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING?
SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM
    customer_shopping_data
GROUP BY
    item_purchased
ORDER BY
    AVG(review_rating) DESC;
---Q4 COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARDS AND EXPRESS
    SELECT shipping_type,
    round(avg(purchase_amount),2)
    from customer_shopping_data
    where shipping_type in ('Standard','Express')
    group by shipping_type
--- Q5 DO SUBSCRIBED CUSTOMERS SPEND MORE ? COMAPARE AVG SPEND AND TOTAL
SELECT subscription_status,
count (customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_shopping_data
group by subscription_status
order by total_revenue, avg_spend desc
--Q6. WHICH PRODUCT HAVE HIGHEST PERCENTAGE WITH DISCOUNTS APPLIED
select item_purchased,
round(100* sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_shopping_data
group by item_purchased
order by discount_rate desc
---Q7 SEGEMENT CUSTOMERS INTO NEW, RETURNING, AND LOYAL BASED ON THEIR TOTAL 
--- NUMBERS OF PRIVOUS PURCHAESE, AND SHOW THE COUNT OF ECAH SEGEMANT
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer_shopping_data
)
select customer_segment ,count(*) as "number of customers"
from customer_type
group by customer_segment
-- Q8 WAHT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHINI EACG CATEGORY?
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer_shopping_data
group by category, item_purchased
)

select item_rank, category , item_purchased,total_orders
from item_counts
where item_rank <= 3
order by category, item_rank;
--Q9 ARE CUSTOMERS WHO ARE REAPEAT (MORE THAN 5 PREVIOUS PURCHAES ALSO LIKELY TO SUBSCRIBE?
SELECT subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_data
where previous_purchases > 5
group by subscription_status

--- Q10 WHAT IS THE REVENUE CONTRIBUTION OF ECAH AGE GROUP?
select age_group,
sum(purchase_amount) as  total_revenue
from customer_shopping_data
group by age_group 
order by total_revenue desc